name: The Pissed Off Report
favicon: null
layout_spectrum: 0.03467916254885495
typography_spectrum: 0.5922970804385841
title: The Pissed Off Report
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f4f4'
    - '#72736e'
    - '#c2c2c2'
    - '#373334'
    - '#a95145'
  brandStrength: 0.83632419584319
  lightness: 0.2216686736792326
  saturation: 0.7073044436983764
  rhythmicContrast: 0.3838493996299803
purpose: []
